### ISSUE TITLE
Build failure on gcc 8.2

### ISSUE THREAD

**Issue by cout** [ddovod/jet-live#6]
Jet-live fails to build with gcc 8.2.

The first problem is straightforward: `-Wvexing-parse` is not supported on gcc 8.2.

The second problem I don't know how to fix; I get the following link errors when building the example:

```
CMakeFiles/example.dir/src/main.cpp.o: In function `std::thread::thread<main::{lambda()#1}>(main::{lambda()#1}&&)':
main.cpp:(.text+0x38c): undefined reference to `pthread_create'
main.cpp:(.text+0x3d4): undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
CMakeFiles/example.dir/src/main.cpp.o: In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<main::{lambda()#1}> > >::~_State_impl()':
main.cpp:(.text+0x648): undefined reference to `std::thread::_State::~_State()'
CMakeFiles/example.dir/src/main.cpp.o: In function `std::thread::_State::_State()':
main.cpp:(.text._ZNSt6thread6_StateC2Ev[_ZNSt6thread6_StateC5Ev]+0x9): undefined reference to `vtable for std::thread::_State'
../liblib_efsw.a(MutexImpl.cpp.o): In function `efsw::Platform::MutexImpl::MutexImpl()':
MutexImpl.cpp:(.text+0x14): undefined reference to `pthread_mutexattr_init'
MutexImpl.cpp:(.text+0x25): undefined reference to `pthread_mutexattr_settype'
../liblib_efsw.a(ThreadImpl.cpp.o): In function `efsw::Platform::ThreadImpl::ThreadImpl(efsw::Thread*)':
ThreadImpl.cpp:(.text+0x31): undefined reference to `pthread_create'
../liblib_efsw.a(ThreadImpl.cpp.o): In function `efsw::Platform::ThreadImpl::wait()':
ThreadImpl.cpp:(.text+0xa1): undefined reference to `pthread_join'
../liblib_efsw.a(ThreadImpl.cpp.o): In function `efsw::Platform::ThreadImpl::terminate()':
ThreadImpl.cpp:(.text+0xd9): undefined reference to `pthread_cancel'
../liblib_tiny-process-library.a(process_unix.cpp.o): In function `std::thread::thread<TinyProcessLib::Process::async_read()::{lambda()#1}>(TinyProcessLib::Process::async_read()::{lam
bda()#1}&&)':
process_unix.cpp:(.text+0x1781): undefined reference to `pthread_create'
process_unix.cpp:(.text+0x17c9): undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
../liblib_tiny-process-library.a(process_unix.cpp.o): In function `std::thread::thread<TinyProcessLib::Process::async_read()::{lambda()#2}>(TinyProcessLib::Process::async_read()::{lam
bda()#2}&&)':
process_unix.cpp:(.text+0x1841): undefined reference to `pthread_create'
process_unix.cpp:(.text+0x1889): undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
../liblib_tiny-process-library.a(process_unix.cpp.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<TinyProcessLib::Process::async_read()::{lambda()#2}> > >::
~_State_impl()':
process_unix.cpp:(.text+0x222e): undefined reference to `std::thread::_State::~_State()'
../liblib_tiny-process-library.a(process_unix.cpp.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<TinyProcessLib::Process::async_read()::{lambda()#1}> > >::
~_State_impl()':
process_unix.cpp:(.text+0x227c): undefined reference to `std::thread::_State::~_State()'
../liblib_tiny-process-library.a(process_unix.cpp.o):(.rodata+0x178): undefined reference to `typeinfo for std::thread::_State'
../liblib_tiny-process-library.a(process_unix.cpp.o):(.rodata+0x1f8): undefined reference to `typeinfo for std::thread::_State'
```

**Comment by ddovod** [comment]
Hi. Could you please try to add a `-pthread` flag to the compile options both for jet-live and example CMakeLists.txt? Like
```
target_compile_options(jet-live
  PRIVATE
  ...
  $<$<COMPILE_LANGUAGE:C>:-pthread>
  $<$<COMPILE_LANGUAGE:CXX>:-pthread>
  )
```
I'll try it myself a bit later today

**Comment by mosra** [comment]
Just FYI, a platform-independent solution would be this:

```cmake
find_package(Threads REQUIRED)
target_link_libraries(jet-live PRIVATE Threads::Threads)
```

It properly handles passing the relevant compiler options as well as linking to pthread. More info: [CMake's FindThreads](https://cmake.org/cmake/help/latest/module/FindThreads.html)

**Comment by ddovod** [comment]
@mosra Thank you very much, just fixed it.
@cout Please try the last revision from master, I've checked it on gcc-6 and gcc-7, works fine on my side, gcc-8.2 should work I guess. Also there's a gcc based build on the travis

**Comment by ddovod** [comment]
Closing, looks like its fine now. Please reopen this issue if something is broken.
